### PR TITLE
added login-signup page

### PR DESCRIPTION
**Pull request by Priyaaa1**

### CODE REVIEW

**Comment by shaktawatpritam2002** [comment]
Good work 👍🏼

**Comment by shaktawatpritam2002** [comment]
cc @ nilesh_jain

**Comment by shaktawatpritam2002** [comment]
sir yahi pe evaluate kardo...har week nahi aayenge ham log..thankyou sir

**Comment by shaktawatpritam2002** [comment]
where is preksha? @Priyaaa1

**Comment by Priyaaa1** [comment]
i don't know

**Comment by Priyaaa1** [comment]
sir ko dikhane se pehle the sb delete kr dena 😥

**Comment by shaktawatpritam2002** [comment]
sir dekhlo...kitni beemani kar rahi hai priya

**Comment by shaktawatpritam2002** [comment]
unsatisfactory likhdo sir isske mein

**Comment by Priyaaa1** [comment]
😭😭

**Comment by Priyaaa1** [comment]
nhii

**Comment by shaktawatpritam2002** [comment]
sir ye dekho ab ye victim card play kar rahi hai

**Comment by shaktawatpritam2002** [comment]
aap daro mat, mein aapke sath hu sir

**Comment by Priyaaa1** [comment]
ab m bnd krke sone jaa rhi

**Comment by Priyaaa1** [comment]
tum sir se baat krte rho

**Comment by shaktawatpritam2002** [comment]
dekhlo sir defend karne ko kuch hai nhi toh jaa rahi hai medaan chord kar

**Comment by shaktawatpritam2002** [comment]
kar har medaan fateh

**Comment by Priyaaa1** [comment]
kr lungi kal

**Comment by shaktawatpritam2002** [comment]
bir bahana mar rahi sir

**Comment by princerajpoot20** [comment]
Hello guyszz

**Comment by princerajpoot20** [comment]
Kya haal chal..need help?

**Comment by Priyaaa1** [comment]
😴

**Comment by princerajpoot20** [comment]
Good evening jain sir 🙏🏻 jai shree ram 🙏🏻

**Comment by princerajpoot20** [comment]
Mein pritam se bikul sehmat hu sir..aap issko iss week absent kardo

**Pull request merged**
